{% set name = "selenium-requests" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5beab478ebea5514264953a8c4a25789b2eeb3741b21b7b78b0823629775fbfc

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - python
    - requests
    - selenium
    - six
    - tldextract

test:
  imports:
    - seleniumrequests

about:
  home: https://github.com/cryzed/Selenium-Requests
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Extends Selenium WebDriver classes to include the request function from the Requests library, while doing all the needed cookie and request headers handling.

extra:
  recipe-maintainers:
    - tsenapathi
