travis:
  secure:
    BINSTAR_TOKEN: lnl4fKvc7IXViNXzLTKAKc7FlRd4Rgi/HX5GTBHgfO3CJg2YrXV3lB2R5XNsJc+aIXvblCVgxzN3NPUrBq6V7p+rAsnrlBTLLo9+MygX4vCENblafDN3Hv2wKVAxeaOs2/XDFpS2x0VgFirAbZc3au9Am7q4+RDrPBUxsNBFJNwUkm2lXai7juH04MAwNPr4aEGAgsLD1VVzMU52gMhNIGFTI/gbueq5qctKwzJ1kqE9bOY+D5KZd9t4u9WFRbS4dV8evaw1GEKXCS5twVlB0E3vG+oOeQ2w4qiqsqjTe4BP3jXSyiJNrmRq59KJHGP6dKWk3vb0k/Cf19eB5FChelGbN85YYxyLrRhjzqvVxncwMgvxappXb1IlH3PUqQy5bgW9oKUFY+c+tyE+KvBfmA71Q1abJglZFlIuWzpi+un4rU0eBBMz5I/OfNOav+PeCbBdpng4+Bh/LyCKaxBXoUyZc2wdO+m/iDRGo+F74hJqHxlXNLZzqlzzjEAKeNKnq4xy7HC9QoPJqDC/gpEz5z8PWxS1y43KhjIjmyArmo/nj/7fkhpceZeIZV4QSHAulWFN6YctPIFU1PlmHCV93KOX5zJ2O1CseYZdtm8O6TFDdn5VgHjnEWVvTxwutq6S8xSKwXdpIerRVRnQHflFv5qVVba9Nf7CCNBOnH82gno=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
